---

- name: RedHat | Install new repository
  yum: name="{{ postgresql_repo }}" state=present
  when: postgresql_repo is defined and postgresql_repo
  register: pkg_result
  until: pkg_result is success

- name: Ensure PostgreSQL packages are installed.
  yum:
    name: "{{ postgresql_pkgnames | default( postgresql_packages ) }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
    # Don't let postgresql-contrib cause the /usr/bin/python symlink
    # to be installed, which breaks later Ansible runs on Fedora 30,
    # and affects system behavior in multiple ways.
    exclude: python-unversioned-command
  register: pkg_result
  until: pkg_result is success

- name: Ensure PostgreSQL Python libraries are installed.
  yum:
    name: "{{ postgresql_python_library }}"
    state: installed
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
  register: pkg_result
  until: pkg_result is success
